apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
       - name: calc
         image: wkandek/calc:6.0
         imagePullPolicy: Always
         env:
           - name: CALC_TESTMODE
             valueFrom:
               configMapKeyRef:
                 name: calc-config
                 key: calc_testmode
         resources:
           requests:
             memory: 100Mi
             cpu: 100m
           limits:
             memory: 100Mi
             cpu: 100m
