apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
       - name: calc
         image: wkandek/calc:2.0
         imagePullPolicy: Always
